#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)


# Meshing 
blockMesh >> log.blockMesh
#runApplication surfaceFeatureExtract 
snappyHexMesh -overwrite >> log.snappy
#runApplication createBaffles -overwrite
createPatch -overwrite >> log.createPatch
mergeOrSplitBaffles -split -overwrite >> log.merge

# Copy fields after meshing to avoid the generation of unnecessary patch fields
cp -r 0.orig 0

# Initialize alpha 
setFields >> log.setFields


#------------------------------------------------------------------------------

unset FOAM_SIGFPE
# Decompose
decomposePar >> log.decomposePar
# Initialize velocity fields
# Run
unset FOAM_SIGFPE

mpirun -np 100 interDyMFoam -parallel >> log.interDyMFoam
#runParallel $application


#------------------------------------------------------------------------------
